import { BoxGeometry, Mesh, MeshStandardMaterial, CanvasTexture } from "three";
import { GLTFExporter } from "three/addons/exporters/GLTFExporter.js";
import { unzipSync } from "fflate";
import { export_tile_glb,export_tile_pack,import_tile_glb,load_tile_assets } from "../src/terrain-assets";
import { tile_template,build_tile_map } from "../src/terrain-tiles";
import { TerrainRenderer } from "../src/terrain-renderer";
import { DSurface,build_hicolor_pixel } from "../src/surface";
import "../src/style.css";
const output=document.querySelector("#log")!;output.textContent="";
const log=(text:string)=>{output.textContent+=`${text}\n`;};
const assert=(value:unknown,message:string)=>{if(!value)throw new Error(message);};
window.addEventListener("unhandledrejection",e=>log(`FAIL: ${e.reason}`));
window.addEventListener("error",e=>log(`FAIL: ${e.message}`));
const tile={ramp:0,tile_type:0,colors:{low:[100,100,100] as [number,number,number],high:[100,100,100] as [number,number,number]},indices:new Uint8Array(576).fill(1),extra:null};
const palette=new Uint16Array(256);palette[0]=31;palette[1]=build_hicolor_pixel(180,120,60);
const tiles={sets:[[tile,tile]],names:["CLEAR01.TEM"],palette,bridge_set:-1,train_bridge_set:-1};
const binary=await export_tile_glb(tiles,0,0), asset=await import_tile_glb(binary), expected=tile_template(tile);
assert(asset.primitives[0]!.vertices.length===expected.length,"Round trip changed triangle count");
for(let i=0;i<expected.length;i++)assert(Math.abs(expected[i]!-asset.primitives[0]!.vertices[i]!)<1e-5,`Round trip changed vertex ${i}`);
const image=asset.primitives[0]!.image!,pixels=image.getContext("2d")!.getImageData(0,0,image.width,image.height).data;
assert(pixels[3]===0,"Transparent PNG corner lost its mask");assert(pixels[(11*48+24)*4]!>150,"Base-color image did not round trip");
const pack=await export_tile_pack(tiles,"TEMPERATE",()=>{},()=>false),files=unzipSync(new Uint8Array(await pack.arrayBuffer()));
assert(files['tiles/temperate/clear01.tem/0.png']&&files['tiles/temperate/clear01.tem/1.glb']&&files['tiles/temperate/clear01.tem/0.json'],"Tile kit missing image, model or metadata");
log("PASS: tile kit PNG + GLB + metadata; geometry, UVs, normals, color and alpha round trip.");
const normal=document.createElement("canvas");normal.width=normal.height=4;const nc=normal.getContext("2d")!;nc.fillStyle="rgb(128,128,255)";nc.fillRect(0,0,4,4);
const map=new CanvasTexture(normal);map.flipY=false;
const material=new MeshStandardMaterial({color:0x16cf95,metalness:0,roughness:1,normalMap:map});
const cube=new Mesh(new BoxGeometry(0.8,0.5,0.8),material);cube.position.set(0.5,0.25,-0.5);cube.rotation.y=0.2;
const replacement=await new GLTFExporter().parseAsync(cube,{binary:true}) as ArrayBuffer;
const parsed=await import_tile_glb(replacement);assert(parsed.primitives[0]!.normal_image,"Normal map lost on import");
assert(parsed.primitives[0]!.vertices.some((v,i)=>i%10===2&&v>0.5),"Node transform was ignored");
const cells=[{x:1,y:1,height:0,tile:0,subtile:0},{x:2,y:1,height:1,tile:0,subtile:1},{x:2,y:2,height:2,tile:0,subtile:0}];
const overrides=new Map([['clear01.tem/0',parsed]]),built=build_tile_map(cells,tiles,overrides);
assert(built.parts[1]!.vertices.length===tile_template(tile).length,"Unreplaced subtile did not retain fallback");
assert(built.parts[0]!.material===built.parts[2]!.material,"Repeated replacement duplicates material identity");
const renderer=new TerrainRenderer(cells,tiles,new Map(),palette,undefined,overrides);
const black=new DSurface(640,400),white=new DSurface(640,400);white.fill(0xffff);
const canvas=document.querySelector<HTMLCanvasElement>("#frame")!;
canvas.getContext("2d")!.drawImage(renderer.render({x:-200,y:-100},640,400,black,white,()=>true),0,0);
const frame=canvas.getContext("2d")!.getImageData(0,0,640,400).data;
assert(frame.some((v,i)=>i%4===1&&v>100&&v>frame[i-1]!+30),"Replacement material was not rendered");
log("PASS: transformed replacement mesh, embedded normal map, repeated placement, mixed fallback and GPU rendering.");
let rejected=false;try{await import_tile_glb(new ArrayBuffer(24));}catch{rejected=true;}assert(rejected,"Corrupt GLB accepted");
let cancelled=false;try{await export_tile_pack(tiles,"TEMPERATE",()=>{},()=>true);}catch{cancelled=true;}assert(cancelled,"Export cancellation ignored");
const discovered=await load_tile_assets("TEMPERATE",cells,tiles,log);
log(`DISCOVERY: ${discovered.size} replacements loaded from the remaster folder.`);
const link=(title:string,name:string,blob:Blob)=>{const a=document.createElement("a");a.textContent=title;a.download=name;a.href=URL.createObjectURL(blob);a.style.marginRight="1rem";document.querySelector("#downloads")!.append(a);};
link("Download synthetic replacement","opents-test-replacement.glb",new Blob([replacement]));
link("Download synthetic tile kit","opents-test-tiles.zip",pack);
log("PASS: corrupt-file rejection and cancellation. Ready for folder-discovery check.");
for(let ramp=0;ramp<=20;ramp++) {
	const ramp_tiles={...tiles,sets:[[{...tile,ramp}]]};
	const imported=await import_tile_glb(await export_tile_glb(ramp_tiles,0,0));
	assert(imported.primitives.length>0,`Ramp ${ramp} exported no editable mesh`);
}
log("PASS: all 21 ramp types produce importable GLB starter meshes.");
