import { BoxGeometry, Mesh, MeshStandardMaterial, CanvasTexture } from "three";
import { GLTFExporter } from "three/addons/exporters/GLTFExporter.js";
import { unzipSync } from "fflate";
import { export_tile_glb,export_tile_pack,import_tile_glb,load_tile_assets } from "../src/terrain-assets";
import { tile_template,tile_prototype,build_tile_map } from "../src/terrain-tiles";
import { TerrainRenderer } from "../src/terrain-renderer";
import { DSurface,build_hicolor_pixel } from "../src/surface";
import "../src/style.css";
const output=document.querySelector("#log")!;output.textContent="";
const log=(text:string)=>{output.textContent+=`${text}\n`;};
const assert=(value:unknown,message:string)=>{if(!value)throw new Error(message);};
window.addEventListener("unhandledrejection",e=>log(`FAIL: ${e.reason}`));
window.addEventListener("error",e=>log(`FAIL: ${e.message}`));
const tile={ramp:0,tile_type:0,colors:{low:[100,100,100] as [number,number,number],high:[100,100,100] as [number,number,number]},indices:new Uint8Array(576).fill(1),extra:null};
const palette=new Uint16Array(256);palette[0]=31;palette[1]=build_hicolor_pixel(180,120,60);
const tiles={sets:[[tile,tile]],names:["CLEAR01.TEM"],palette,bridge_set:-1,train_bridge_set:-1};
const binary=await export_tile_glb(tiles,0,0), asset=await import_tile_glb(binary), expected=tile_prototype(tiles,0,0);
const glbHeader=new DataView(binary), glbJson=JSON.parse(new TextDecoder().decode(new Uint8Array(binary,20,glbHeader.getUint32(12,true))));
const glbPrimitive=glbJson.meshes[0].primitives[0];
assert(glbJson.accessors[glbPrimitive.attributes.POSITION].count===4 && glbJson.accessors[glbPrimitive.indices].count===6,"Flat GLB must contain four shared corners and two triangles");
assert(asset.primitives[0]!.vertices.length===expected.length,"Round trip changed triangle count");
for(let i=0;i<expected.length;i++)assert(Math.abs(expected[i]!-asset.primitives[0]!.vertices[i]!)<1e-5,`Round trip changed vertex ${i}`);
const image=asset.primitives[0]!.image!,pixels=image.getContext("2d")!.getImageData(0,0,image.width,image.height).data;
assert(pixels[3]===255,"Generated ground should be opaque");assert(pixels[0]!>150,"Base-color image did not round trip");
const pack=await export_tile_pack(tiles,"TEMPERATE",()=>{},()=>false),files=unzipSync(new Uint8Array(await pack.arrayBuffer()));
assert(files['tiles/temperate/clear01.tem/0.png']&&files['tiles/temperate/clear01.tem/1.glb']&&files['tiles/temperate/clear01.tem/0.json'],"Tile kit missing image, model or metadata");
const original=await createImageBitmap(new Blob([files['tiles/temperate/clear01.tem/0.png']! as Uint8Array<ArrayBuffer>],{type:"image/png"}));
const originalCanvas=document.createElement("canvas");originalCanvas.width=original.width;originalCanvas.height=original.height;
const originalContext=originalCanvas.getContext("2d")!;originalContext.drawImage(original,0,0);original.close();
assert(originalContext.getImageData(0,0,1,1).data[3]===0,"Separate original PNG must retain transparency");
log("PASS: tile kit PNG + GLB + metadata; geometry, UVs, normals, color and alpha round trip.");
const normal=document.createElement("canvas");normal.width=normal.height=4;const nc=normal.getContext("2d")!;nc.fillStyle="rgb(128,128,255)";nc.fillRect(0,0,4,4);
const map=new CanvasTexture(normal);map.flipY=false;
const material=new MeshStandardMaterial({color:0x16cf95,metalness:0,roughness:1,normalMap:map});
const cube=new Mesh(new BoxGeometry(0.8,0.5,0.8),material);cube.position.set(0.5,0.25,-0.5);cube.rotation.y=0.2;
const replacement=await new GLTFExporter().parseAsync(cube,{binary:true}) as ArrayBuffer;
const parsed=await import_tile_glb(replacement);assert(parsed.primitives[0]!.normal_image,"Normal map lost on import");
assert(parsed.primitives[0]!.vertices.some((v,i)=>i%10===2&&v>0.5),"Node transform was ignored");
const cells=[{x:1,y:1,height:0,tile:0,subtile:0},{x:2,y:1,height:1,tile:0,subtile:1},{x:2,y:2,height:2,tile:0,subtile:0}];
const overrides=new Map([['clear01.tem/0',parsed]]),built=build_tile_map(cells,tiles,overrides);
assert(built.parts[1]!.vertices.length===tile_template(tile).length,"Unreplaced subtile did not retain fallback");
assert(built.parts[0]!.material===built.parts.at(-1)!.material,"Repeated replacement duplicates material identity");
const renderer=new TerrainRenderer(cells,tiles,new Map(),palette,undefined,overrides);
const black=new DSurface(640,400),white=new DSurface(640,400);white.fill(0xffff);
const canvas=document.querySelector<HTMLCanvasElement>("#frame")!;
canvas.getContext("2d")!.drawImage(renderer.render({x:-200,y:-100},640,400,black,white,()=>true),0,0);
const frame=canvas.getContext("2d")!.getImageData(0,0,640,400).data;
assert(frame.some((v,i)=>i%4===1&&v>100&&v>frame[i-1]!+30),"Replacement material was not rendered");
log("PASS: transformed replacement mesh, embedded normal map, repeated placement, mixed fallback and GPU rendering.");
let rejected=false;try{await import_tile_glb(new ArrayBuffer(24));}catch{rejected=true;}assert(rejected,"Corrupt GLB accepted");
let cancelled=false;try{await export_tile_pack(tiles,"TEMPERATE",()=>{},()=>true);}catch{cancelled=true;}assert(cancelled,"Export cancellation ignored");
const discovered=await load_tile_assets("TEMPERATE",cells,tiles,log);
log(`DISCOVERY: ${discovered.size} replacements loaded from the remaster folder.`);
const link=(title:string,name:string,blob:Blob)=>{const a=document.createElement("a");a.textContent=title;a.download=name;a.href=URL.createObjectURL(blob);a.style.marginRight="1rem";document.querySelector("#downloads")!.append(a);};
link("Download synthetic replacement","opents-test-replacement.glb",new Blob([replacement]));
link("Download synthetic tile kit","opents-test-tiles.zip",pack);
log("PASS: corrupt-file rejection and cancellation. Ready for folder-discovery check.");
for(let ramp=0;ramp<=20;ramp++) {
	const ramp_tiles={...tiles,sets:[[{...tile,ramp}]]};
	const imported=await import_tile_glb(await export_tile_glb(ramp_tiles,0,0));
	assert(imported.primitives.length>0,`Ramp ${ramp} exported no editable mesh`);
}
log("PASS: all 21 ramp types produce importable GLB starter meshes.");
const cliffTiles={...tiles,sets:[[{...tile,record_height:4,location:{x:0,y:0}},
	{...tile,record_height:0,location:{x:1,y:0},extra:{dx:0,dy:-48,width:24,height:60,indices:new Uint8Array(1440).fill(1)}}]]};
const cliff=await import_tile_glb(await export_tile_glb(cliffTiles,0,0)), cliffExpected=tile_prototype(cliffTiles,0,0);
assert(cliffExpected.length===120,"Cliff starter should contain two ground and two wall triangles");
for(let i=0;i<cliffExpected.length;i++) assert(Math.abs(cliffExpected[i]!-cliff.primitives[0]!.vertices[i]!)<1e-5,`Cliff GLB changed vertex ${i}`);
log("PASS: four-corner indexed flat GLB and connected cliff wall geometry survive export/import; original PNG alpha is preserved.");

const one=await export_tile_pack(tiles,'TEMPERATE',()=>{},()=>false,[{tile:65535,subtile:1}]);
const oneFiles=unzipSync(new Uint8Array(await one.arrayBuffer()));
assert(Object.keys(oneFiles).length===4&&oneFiles['tiles/temperate/clear01.tem/1.glb'],'Selected tile ZIP included other tiles or lost its canonical identity');
const edited=await export_tile_pack(tiles,'TEMPERATE',()=>{},()=>false,[{tile:0,subtile:0}],new Map([['clear01.tem/0',parsed]]));
const editedFiles=unzipSync(new Uint8Array(await edited.arrayBuffer()));
assert(editedFiles['tiles/temperate/clear01.tem/0.glb']!.every((v,i)=>v===new Uint8Array(replacement)[i]),'Export discarded the installed replacement');
const isolatedCells=[{x:8,y:9,height:4,tile:0,subtile:0},{x:9,y:9,height:0,tile:0,subtile:1}];
const isolatedMesh=build_tile_map(isolatedCells,tiles);
const selectedPack=await export_tile_pack(tiles,'TEMPERATE',()=>{},()=>false,[isolatedCells[0]!],new Map(),isolatedMesh);
const selectedFiles=unzipSync(new Uint8Array(await selectedPack.arrayBuffer()));
const selectedGLB=selectedFiles['tiles/temperate/clear01.tem/0.glb']!;
const selectedAsset=await import_tile_glb(selectedGLB.slice().buffer as ArrayBuffer);
assert(selectedAsset.primitives[0]!.vertices.length===120,'Selected cliff lost map boundary walls');
const local=selectedAsset.primitives[0]!.vertices;
for(let i=0;i<local.length;i+=10)assert(local[i]!>=0&&local[i]!<=1&&local[i+1]!>=0&&local[i+1]!<=1&&local[i+2]!>=-4&&local[i+2]!<=0,'Selected tile still has map translation/elevation');
log('PASS: single-tile ZIP, clear-tile identity, preservation of edited GLB, and map cliff export in local coordinates.');
